### PR TITLE
Python->C++ exception translation

### LINKED ISSUE #947: Python exception translation
## What

Ensure information is not lost from Python exceptions when bridged to C++

Also see #866 (duplicate issue)

## Why

We currently lose information about Python exceptions when caught in C++.

When Python code calls a C++ function, and that C++ function raises an exception, there is a built-in hook via pybind11 to translate the C++ exception to a Python exception (see usages of `register_exception_translator`).

However, when C++ calls a Python function, and that Python function raises an exception, pybind11 will detect the Python exception and throw an (unhelpfully named) `error_already_set` exception. There is no pybind11 hook available to modify this. 

In this case, consumers (hosts or manager plugins) must catch `std::exception` and interrogate the `what()` string to disambiguate.

We really need to devise a way to translate Python exceptions to the appropriate C++ exceptions, so that consumers can disambiguate using the exception type (i.e. in `catch` blocks).

An unfortunate wrinkle is in the special status that pybind11's `error_already_set` exception has within pybind11 itself. If this exception propagates _back_ into Python, then the original Python exception is restored, complete with stack trace etc.

So ideally we would only conditionally translate an `error_already_set` exception into a more appropriate C++ exception, by somehow figuring out whether the exception will be caught in C++ or Python code.

## ACs 

- Define approach for the above

### PR DESCRIPTION
**Pull request by feltech**
## Description

Closes #947. Establish a strategy for single-sourcing Python<->C++ exception mapping, add a mechanism to translate OpenAssetIO-specific Python exceptions to corresponding C++ exceptions, and augment the pybind11 override macros to do the translation.

This only affects pybind11 "trampoline" functions - i.e. C++ virtual methods that can call out to a Python implementation.

- [x] I have updated the release notes.
- [x] I have updated all relevant user documentation.

## Reviewer Notes

The final commit is optional. A comment in the GitHub issue mentions `createPythonPluginSystemManagerImplementationFactory`, so the final commit was added to be able to use the new functionality there. However, on inspection it didn't actually seem necessary.

Testing every affected class isn't tackled. Instead, the macros are tested via dedicated contrived `cmodule` (`_openassetio_test`) tests. Testing for all classes can be added if it seems worthwhile, but will be a big chunk of code (similar to the GIL tests). Otherwise, we're OK as long as we trust contributors to always use the `OPENASSETIO_`-prefixed pybind11 macros (as detailed in the CODING_STANDARDS).

Only OpenAssetIO-specific exceptions are converted.  It wouldn't be much extra effort to also cover other  exceptions.

### CODE REVIEW

File: src/openassetio-core/include/openassetio/errors/exceptions.hpp [hunk 1]
```diff
@@ -107,6 +108,12 @@ struct OPENASSETIO_CORE_EXPORT BatchElementException : OpenAssetIOException {
   BatchElementError error;
 };
 
+/// List of all OpenAssetIO-specific exceptions. Used in Python
+/// exception translation.
```
Comment (foundrytom) [inline src/openassetio-core/include/openassetio/errors/exceptions.hpp:112]: [Consider][minor] As this is core, maybe mention languages more generically if the intention is to enable more programatic binding generation for any target language?

File: src/openassetio-core/include/openassetio/errors/exceptions.hpp [hunk 2]
```diff
@@ -107,6 +108,12 @@ struct OPENASSETIO_CORE_EXPORT BatchElementException : OpenAssetIOException {
...
+using AllExceptions =
+    std::tuple<OpenAssetIOException, InputValidationException, ConfigurationException,
+               NotImplementedException, UnhandledException>;
```
Comment (foundrytom) [inline src/openassetio-core/include/openassetio/errors/exceptions.hpp:115]: [Question] Why isn't `BatchElementException` here?

File: src/openassetio-python/private/include/openassetio/private/python/exceptions.hpp [hunk 3]
```diff
@@ -0,0 +1,362 @@
...
+ *
+ * @tparam I Indices of exceptions in AllExceptions.
+ */
+template <std::size_t... I>
+constexpr bool assertAllExceptionsAreInList([[maybe_unused]] std::index_sequence<I...> unused) {
+  (assertExceptionIsInList<I>(CppExceptionsAndPyClassNames::kIndices), ...);
+  return true;
+}
+/**
+ * Assert that all exceptions in the AllExceptions list are also found
```
Comment (foundrytom) [inline src/openassetio-python/private/include/openassetio/private/python/exceptions.hpp:201]: [Consider][minor] For a new reader, it might be nice to differentiate that the above are the mechanism by which the last actually does the assertion.

```suggestion
 * Execute compile-time assertions that all exceptions in the AllExceptions list are also found
```

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 4]
```diff
@@ -11,87 +14,376 @@
...
+ * @param mod Python module to hold new Python exception class.
+ * @param registeredExceptions Previously registered exceptions, to use
+ * when looking up Python base class to inherit from, and to add this
+ * exception to once registered.
+ */
+template <>
+void registerPyExceptionClass<ConfigurationException>(const std::string_view pyClassName,
+                                                      const py::module_ &mod,
+                                                      PyObjectByName &registeredExceptions) {
+  const py::object pyBaseClass = registeredExceptions.at("InputValidationException");
```
Comment (foundrytom) [inline src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:166]: [question][naive] Thinking out loud, from a very uninformed starting point, could you use `kCppExceptionsAndPyClassNames` to auto-derive `pyBaseClass` from the introspected base of the template so you dont need a specialisations? Might not be worth it.

File: src/openassetio-python/tests/cmodule/test_errors.py [hunk 5]
```diff
@@ -66,3 +70,82 @@ def test_when_ConfigurationException_thrown_then_can_be_caught_as_InputValidatio
...
+            errors.BatchElementError.ErrorCode.kInvalidEntityReference, "Explosion!"
+        )
+        exception = exception_type(123, error, "Another explosion!")
+    else:
+        exception = exception_type("Explosion!")
+
+    return exception
+
+
+class PyExceptionThrower(_openassetio_test.ExceptionThrower):
```
Comment (foundrytom) [inline src/openassetio-python/tests/cmodule/test_errors.py:131]: [Consider] This is really well documented in c++ - might be worth a cursory note here on what this is doing and how.

File: doc/contributing/CODING_STANDARDS.md [hunk 6]
```diff
@@ -232,6 +232,25 @@ a null pointer.
...
+class implementation if no Python override is found. Method bodies
+use convenience macros to implement this logic.
+
+In pybind11, any exception that occurs in Python, and propagates to C++,
+is translated to an `error_already_set` C++ exception. In order to
+support Python->C++ exception type translation, we must augment the
+pybind11 macros.
+
+So instead of using the `PYBIND11_OVERRIDE_*` family of macros, we must
+use `OPENASSETIO_PYBIND11_OVERRIDE_*`, which decorates the pybind11
```
Comment (foundrytom) [inline doc/contributing/CODING_STANDARDS.md:250]: [question] if wonder if its worth a grep test in CI to assert this? like we do for OAIO?

**Review by foundrytom — COMMENTED** [review]
Only superficial comments from me as others are far better placed to comment on the implementation. But great job on the thoroughness of approach/testing. Minor Q - would you imagine squashing the last two commits into the previous commit-but-one?

**Comment by foundrytom** [comment]
> . A comment in the GitHub issue mentions createPythonPluginSystemManagerImplementationFactory, so the final commit was added to be able to use the new functionality there. However, on inspection it didn't actually seem necessary.

I think the intent was that that code could raise OpenAssetIO exceptions from Python, that would end up in C++.

**Comment by feltech** [comment]
> > . A comment in the GitHub issue mentions createPythonPluginSystemManagerImplementationFactory, so the final commit was added to be able to use the new functionality there. However, on inspection it didn't actually seem necessary.
> 
> I think the intent was that that code could raise OpenAssetIO exceptions from Python, that would end up in C++.

Yeah that was the thought, but looking at the code, no OpenAssetIO exceptions can be raised there. We could wrap the construction of `PythonPluginSystemManagerImplementationFactory` just in case we modify the Python constructor in future to raise an OpenAssetIO exception?

The `instantiate` method is already covered because it's pybind11 trampoline method. It was just potentially the constructor that's not covered.

**Comment by feltech** [comment]
> Minor Q - would you imagine squashing the last two commits into the previous commit-but-one?

Yeah I guess that would make the history a bit easier to grok, assuming we're happy to keep the new shared private header, even though its not currently necessary.

**Comment by foundrytom** [comment]
> Yeah that was the thought, but looking at the code, no OpenAssetIO exceptions can be raised there. We could wrap the construction of `PythonPluginSystemManagerImplementationFactory` just in case we modify the Python constructor in future to raise an OpenAssetIO exception?

Ahh yes - maybe we need to worry about `ManagerInterfaceFactoryInterface` then? As that calls into Python?

**Comment by foundrytom** [comment]
> Ahh yes - maybe we need to worry about `ManagerInterfaceFactoryInterface` then? As that calls into Python?

Oh and `PagerInterface`? And anything else like that? Ie many of the places we had to touch the GIL?

File: src/openassetio-python/cmodule/src/_openassetio.hpp [hunk 7]
```diff
@@ -20,10 +20,33 @@ OPENASSETIO_FWD_DECLARE(log, LoggerInterface)
 OPENASSETIO_FWD_DECLARE(hostApi, HostInterface)
 OPENASSETIO_FWD_DECLARE(hostApi, ManagerImplementationFactoryInterface)
 
+/// @note Update errorsTest.cpp if adding more override macros below.
+
+/**
+ * Decorate PYBIND11_OVERRIDE_NAME with exception type translation.
+ */
+#define OPENASSETIO_PYBIND11_OVERRIDE_NAME(ret_type, cname, name, fn, ...)                      \
```
Comment (elliotcmorris) [inline src/openassetio-python/cmodule/src/_openassetio.hpp]: [Consider] I might think about defining these in their own place within the cmodule dir, `exception_translation_macros.hpp` or something. They get in the way of the "point" of this file imo.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 8]
```diff
@@ -462,3 +462,129 @@ void registerExceptions(const py::module &mod) {
...
+ * to @p Exception class.
+ * @param thrownPyExc pybind11-wrapped Python exception to potentially
+ * wrap in a HybridException.
+ * @param thrownPyExcName Python exception class name of @p thrownPyExc
+ * to test against @p expectedPyExcName.
+ */
+template <class Exception>
+void throwHybridExceptionIfMatches(const std::string_view expectedPyExcName,
+                                   const py::error_already_set &thrownPyExc,
+                                   const std::string_view thrownPyExcName) {
```
Comment (elliotcmorris) [inline src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: [Consider] could you extract the name from the PyExc here in the function, rather than require an external extraction and argument pass??

**Review by elliotcmorris — CHANGES_REQUESTED** [review]
Really solid engineering imo. I couldn't have done this as well.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 9]
```diff
@@ -11,87 +14,376 @@
...
+ */
 
-void registerBatchElementException(const py::module &mod) {
-  // Pybind has very limited support for custom exception types. This is
-  // a well-known tricky issue and is apparently not on the roadmap to
-  // fix. The only direct support is for an exception type that takes a
-  // single string parameter (message). However, we need `index` and
-  // `error` parameters to mirror C++.
+/**
+ * @section topy Conversion from C++ exception to Python exception.
```
[the remark this answers is not in the document]
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:25]: Oh no it's not. its To-py, Doh!

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 4 above)
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:166]: Heh, i noted in my review how I thought resisting the urge to do this was a good call :P.
Either works, but don't let the genericism override the clarity.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 10]
```diff
@@ -11,87 +14,376 @@
...
+ * identifiers.
+ *
+ * @tparam Type List of types.
+ */
+template <class... Type>
+struct TypesAndIds {
+  static constexpr std::size_t kSize = sizeof...(Type);
+  using Types = std::tuple<Type...>;
+  const std::array<std::string_view, kSize> ids;
+};
```
[the remark this answers is not in the document]
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Not actually sure how that works, if std::array would reject an initializer list or a vector of innapropriate size, or if there'd be an implicit conversion leaving some empty string views on the end.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 11]
```diff
@@ -11,87 +14,376 @@
...
+/// Mapping of Python class name to Python class object.
+using PyObjectByName = std::map<const std::string_view, const py::object>;
+
+/**
+ * Register a new Python exception.
+ *
+ * General case of a simple exception (only takes a single string
+ * constructor argument) with OpenAssetIOException as its base class.
+ *
+ * @tparam Exception Corresponding C++ exception type.
```
[the remark this answers is not in the document]
Comment (hartmutbehrens) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:117]: `tparam` -> template parameter, so probably fine.

**Comment by feltech** [comment]
> > Ahh yes - maybe we need to worry about `ManagerInterfaceFactoryInterface` then? As that calls into Python?
> 
> Oh and `PagerInterface`? And anything else like that? Ie many of the places we had to touch the GIL?

As long as calling out to Python from C++ is done transparently via a C++ base class virtual method (i.e. pybind11 trampoline), then exceptions raised in Python will be translated, due to the new/updated `OPENASSETIO_PYBIND11_OVERRIDE*` macros.

If there are places where we explicitly call a method on a `py::object`, then we'd need to decorate that call to translate any OpenAssetIO exceptions that propagate out of it.  But I don't think we do this anywhere, apart from `createPythonPluginSystemManagerImplementationFactory`?

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Yeah it fails at compile time if you try to give too few or too many elements to the array.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 12]
```diff
@@ -11,87 +14,376 @@
...
+ *
+ * In particular there are two lists, such that given a single index,
+ * the C++ exception class or the Python class name can be queried at
+ * compile time.
+ */
+struct CppExceptionsAndPyClassNames {
+  using Type = decltype(kCppExceptionsAndPyClassNames);
+  /// "Array" of C++ exception classes.
+  template <std::size_t I>
+  using Exceptions = std::tuple_element_t<I, typename Type::Types>;
```
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Yeah the idea was to make it "look" like an array when used, especially when using `kClassNames` and `Execptions` together with the same index.

I think `std::get` only retrieves values, as opposed to types. Maybe it has specialisations, will take a look.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 13]
```diff
@@ -11,87 +14,376 @@
...
+/**
+ * Execute compile-time assertions that no class in the
+ * CppExceptionsAndPyClassNames list has a base class at a lower index
+ * in the list.
+ *
+ * The resulting value is unused - it's just kludge to make the
+ * compiler make the attempt and so fail on any violated static_asserts.
+ */
+[[maybe_unused]] constexpr bool kIsClassListOrderValid =
+    assertClassesAreInHierarchyOrder(CppExceptionsAndPyClassNames::kIndices);
```
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Oh interesting, odd kinda no-op assert, but getting rid of the pointless variable would be good.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 14]
```diff
@@ -11,87 +14,376 @@
...
+   */
+  static constexpr auto kIndices = std::make_index_sequence<kSize>{};
+};
+
+/**
+ * @}
+ */
+
+/**
+ * @section asserts Compile-time assertions.
```
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: I'm not keen on that, since the `exceptionsValidation.hpp` header on its own would have lots of red squiggles in my editor (since it depends on stuff defined "above").

I am keen on finding a way to hide some of this assertion logic though, since I totally agree it causes issues with readability.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 15]
```diff
@@ -11,87 +14,376 @@
...
+void tryCatch<0>(const py::module_ &pyModule, std::exception_ptr pexc) {
+  try {
+    std::rethrow_exception(std::move(pexc));
+  } catch (CppExceptionsAndPyClassNames::Exceptions<0> &cppExc) {
+    setPyException(cppExc, pyModule, CppExceptionsAndPyClassNames::kClassNames[0]);
+  }
+}
+
+/// Mapping of Python class name to Python class object.
+using PyObjectByName = std::map<const std::string_view, const py::object>;
```
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:109]: I tried `unordered_map`, but `std::string_view` wouldn't work as a key.  I assumed there was no `std::hash` overload.  A quick google implies that's not the case and it should be possible, though, so I'll take another look.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:166]: Similar to Tom's comment: https://github.com/OpenAssetIO/OpenAssetIO/pull/1190#discussion_r1389127543 - it's a nice idea, will take a look and see if it's straightforward enough.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 8 above)
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Could do, but it would be repeated multiple times (once for every call) rather than once in the caller and passed in.

**Comment by foundrytom** [comment]
> As long as calling out to Python from C++ is done transparently via a C++ base class virtual method (i.e. pybind11 trampoline), then exceptions raised in Python will be translated, due to the new/updated `OPENASSETIO_PYBIND11_OVERRIDE*` macros.

Oh nice, I hadn't realised we were already using our custom macros there, so 👍 Does [this](https://github.com/OpenAssetIO/OpenAssetIO/pull/1190#issuecomment-1805633069) need one thought?

**Comment by feltech** [comment]
> Does [this](https://github.com/OpenAssetIO/OpenAssetIO/pull/1190#issuecomment-1805633069) need one thought?

I'm not sure what you mean? Were you meant to link to a different comment?

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 8 above)
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Isn't that already the case? Looks like `throwHybridExceptionIfMatches` is only called from inside `convertPyExceptionAndThrow`, and the extraction is being done each time that function is being called anyway.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: `std::decay_t<decltype(std::get<I>(std::declval<Type::Types>()))>` :laughing: - I think the existing version is a bit neater.

**Comment by foundrytom** [comment]
> > Does [this](https://github.com/OpenAssetIO/OpenAssetIO/pull/1190#issuecomment-1805633069) need one thought?
> 
> I'm not sure what you mean? Were you meant to link to a different comment?

Sorry no idea what went on there, the link was meant to be https://github.com/OpenAssetIO/OpenAssetIO/blob/2198d02b8415785effb779ed76eba78ed6362fb9/src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp#L40

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 8 above)
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: But `convertPyExceptionAndThrow` is only called once.

**Comment by feltech** [comment]
> Sorry no idea what went on there, the link was meant to be
> 
> https://github.com/OpenAssetIO/OpenAssetIO/blob/2198d02b8415785effb779ed76eba78ed6362fb9/src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp#L40

Still not sure I follow. `EntityReferencePagerInterfaceBinding.cpp` already used/has been updated to use `OPENASSETIO_*` macros.

File: src/openassetio-core/include/openassetio/errors/exceptions.hpp (hunk 1 above)
Comment (feltech) [reply src/openassetio-core/include/openassetio/errors/exceptions.hpp]: Made more generic in b1373437

File: src/openassetio-python/private/include/openassetio/private/python/exceptions.hpp (hunk 3 above)
Comment (feltech) [reply src/openassetio-python/private/include/openassetio/private/python/exceptions.hpp]: Updated docstring as suggested in 960a54e4

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 4 above)
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Had some fun in f4993c24 - can drop if you think it's excessive (it only helps remove a single case). It does have the neat side-effect of ensuring that the Python class hierarchy mirrors C++.

File: src/openassetio-python/tests/cmodule/test_errors.py (hunk 5 above)
Comment (feltech) [reply src/openassetio-python/tests/cmodule/test_errors.py:131]: Added a docstring in 9103b05c

File: doc/contributing/CODING_STANDARDS.md (hunk 6 above)
Comment (feltech) [reply doc/contributing/CODING_STANDARDS.md:250]: Yeah good idea. I was thinking we could change the `business-language` check to `disallowed-phrases` and add it there. Could also be useful if/when we do inclusive terminology checks too.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 13 above)
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Simplified as suggested in 13b69491

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp [hunk 16]
```diff
@@ -11,87 +14,376 @@
...
+                    const std::string_view pyClassName) {
+  const py::object pyClass = pyModule.attr(pyClassName.data());
+  const py::object pyInstance = pyClass(exception.what());
+  PyErr_SetObject(pyClass.ptr(), pyInstance.ptr());
+}
+
+/**
+ * Set the current Python exception in this thread.
+ *
+ * Overload to handle more complex case of BatchElementException.
```
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp:54]: With the change in https://github.com/OpenAssetIO/OpenAssetIO/pull/1190#discussion_r1389127543 there are only two special cases remaining (`OpenAssetIOException` and `BatchElementException`), and handling them all in the same method could remove a little duplication.

Will have to sketch it out and see if how neat it looks.

File: src/openassetio-python/cmodule/src/_openassetio.hpp (hunk 7 above)
Comment (feltech) [reply src/openassetio-python/cmodule/src/_openassetio.hpp]: Good idea, they are using up a lot of space now. The `_openassetio.hpp` has become a bit of a dumping ground.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 4 above)
Comment (foundrytom) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: > It does have the neat side-effect of ensuring that the Python class hierarchy mirrors C++.

For me thats a useful benefit, as it makes future maintenance easier and less prone to human error. @elliotcmorris what are your thoughts?

**Comment by foundrytom** [comment]
> > Sorry no idea what went on there, the link was meant to be
> > https://github.com/OpenAssetIO/OpenAssetIO/blob/2198d02b8415785effb779ed76eba78ed6362fb9/src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp#L40
> 
> Still not sure I follow. `EntityReferencePagerInterfaceBinding.cpp` already used/has been updated to use `OPENASSETIO_*` macros.

Sorry I had somehow slipped back to browsing `main` not your tree.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Yep, me too :P

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Resolving in favour of the other thread.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Yeah that's a fair point.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Updated in a16f9571 - the trick was to get rid of the `const` from the key type.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (feltech) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: `if constexpr`ed a bunch in 8de8f03a.  I'm two minds about `registerPyExceptionClass` - it only saves one line of duplication, at the expense of a biig function (albeit mostly comments), but it does at least keep it all together. What do you think?

File: src/openassetio-python/cmodule/src/_openassetio.hpp (hunk 7 above)
Comment (feltech) [reply src/openassetio-python/cmodule/src/_openassetio.hpp]: Good call. Put in their own header in a8e8db56 - much nicer and YAGNI.

File: doc/contributing/CODING_STANDARDS.md (hunk 6 above)
Comment (feltech) [reply doc/contributing/CODING_STANDARDS.md:250]: CI job updated in 18647406

Showing that "OAIO" is still caught: https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/6876912503/job/18703496245?pr=1190

Showing that bad pybind11 macros is caught: https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/6876921789/job/18703536758?pr=1190

The ID of the job has changed and its a required check, so we can either change the ID back or update the project settings.

Comment (foundrytom) [reply doc/contributing/CODING_STANDARDS.md:250]: Awesome sauce. The new name is better so we can just update the branch protection requirement.

**Review by foundrytom — APPROVED** [review]

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 4 above)
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: > It does have the neat side-effect of ensuring that the Python class hierarchy mirrors C++.

Suppose that's fair. It's not really that much more complicated either.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: I like the smaller ones above, I think that's an improvement. But I see what you mean about `registerPyExceptionClass`. I do think the if/else fallthrough logic is easier to understand than specialisation dispatch though, despite being a bit less elegant feeling.

File: src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp (hunk 8 above)
Comment (elliotcmorris) [reply src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp]: Resolving this as it's not important, even though i still don't quite follow the argument... probably just text chat fog-of-war.

**Review by elliotcmorris — APPROVED** [review]

**Comment by feltech** [comment]
I've squashed down the commits, in case anyone wants to check the commit messages/breakdown makes sense.

I've also added a fixup 7ec0b72d to move the static assertions to their own .cpp file, since I figured they were obscuring the public interface of the header, and pessimised build times by re-running the static assertions in every translation unit that included it.

**Review by foundrytom — APPROVED** [review]
Great idea @feltech - like it.
