### PR TITLE
[Core] Add BatchElementError

### LINKED ISSUE #557: `BatchElementError` type for callback-based batch methods
# What

Add a `BatchElementError` class to be used in error callbacks for batch-first API methods.

# Why

Our batch-first design means that errors that affect only a single element of the batch should not cause the whole batch to fail. Instead, such errors are communicated via an error callback, with a unique call per failed batch element.

We need some way for the manager to communicate the reason for a failure to the error callback. In order for this to be extensible we need to bundle the error details into a class.  At minimum these details will include an error code and message, giving the same level of information as a standard exception.

# ACs

* A header containing error codes in the core library that is importable in the C library, in order to prevent duplication of error codes. 
  - This should not have a dependency on the C library/headers.  
  - Initially supporting only "kUnknown".
  - Do not overlap these new error codes with the exception error codes.
* `BatchElementError` value semantic struct containing
  - `enum class ErrorCode` (initially) supporting only "kUnknown".
  - Error code value, `const ErrorCode code`.
  - Error message value `const std::string message`.
* C API sketch

# Out of scope

* New error codes.

### PR DESCRIPTION
**Pull request by feltech**
Closes #557.

Add a simple `BatchElementError` aggregate class, initially containing just an error code and string message. The error code is a strongly typed enumeration, currently only supporting a fallback code of `kUnknown`.

To prevent ambiguity of these error codes with the C API's exception error codes, and to allow reuse of the error codes between C++ and C, add a new C-compatible header the core library, with `#define`s computing the new error codes as offset from the C API's exception error codes.

### CODE REVIEW

File: src/openassetio-core/include/openassetio/BatchElementError.hpp [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+  /// Possible classes of error.
+  enum class ErrorCode {
+    /// Fallback for uncommon errors.
+    kUnknown = OPENASSETIO_BatchErrorCode_kUnknown
+  };
+
+  /// Error code indicating the class of error.
+  const ErrorCode code;
+  /// Human-readable error message.
+  const Str message;
```
Comment (foundrytom) [inline src/openassetio-core/include/openassetio/BatchElementError.hpp:48]: [fix] Can we change this to `std::string` based on the char around that whole world, save revisiting own the not too distant.

File: src/openassetio-core/include/openassetio/errors.h [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+ * exception-like errors.
+ */
+#define OPENASSETIO_ErrorCode_BEGIN 1
+
+/**
+ * First error code used for representing a batch element error.
+ *
+ * Assumes a maximum of 100 exception-like error codes before these.
+ */
+#define OPENASSETIO_BatchErrorCode_BEGIN (OPENASSETIO_ErrorCode_BEGIN + 100)
```
Comment (foundrytom) [inline src/openassetio-core/include/openassetio/errors.h:27]: [question] Is there any merit in making this some power of 2?

**Review by foundrytom — CHANGES_REQUESTED** [review]

File: src/openassetio-core/include/openassetio/errors.h (hunk 2 above)
Comment (feltech) [reply src/openassetio-core/include/openassetio/errors.h:27]: :thinking: Interesting. Off the top of my head, we _could_ use bit-masking/shifting instead of inequality to test if a given error code is exception-like or batch element-like, but the additional boilerplate makes that not so useful. 

Anything else you can think of?

File: src/openassetio-core/include/openassetio/BatchElementError.hpp (hunk 1 above)
Comment (feltech) [reply src/openassetio-core/include/openassetio/BatchElementError.hpp]: Updated in 0876e51a

File: src/openassetio-core/include/openassetio/errors.h (hunk 2 above)
Comment (foundrytom) [reply src/openassetio-core/include/openassetio/errors.h:27]: Yeah I think that is what was lurking around in my mind - that it would might make it easier to work out what 'class' of code it was? But as they're never meant to be used in the same context - do we think we'd ever have a use case?

File: src/openassetio-core/include/openassetio/BatchElementError.hpp [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+/**
+ * Structure representing per-element batch operation errors.
+ *
+ * Many OpenAssetIO API functions take multiple inputs, i.e. a batch of
+ * elements, in order to allow the @ref manager backend to optimise bulk
+ * queries. The results of such queries are usually returned
+ * element-by-element via a callback.
+ *
+ * It is possible for the whole batch to fail due to some catastrophic
+ * error, in which case a standard exception workflow is expected.
```
Comment (foundrytom) [inline src/openassetio-core/include/openassetio/BatchElementError.hpp:22]: [consider] Based on our chat earlier about BAL, I was looking into HTTP status codes. They separate [Client Errors - 4xx](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) from [Server Errors - 5xx](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses). This feels like the axis we've been grasping for when trying to work out what is a `BatchElementError` and what is an exception. Might be good to add this as a concrete example here as to when to use `BatchElementError`?

File: src/openassetio-core/include/openassetio/errors.h (hunk 2 above)
Comment (feltech) [reply src/openassetio-core/include/openassetio/errors.h]: Doesn't do any harm, tweaked in 84f7f84a

File: src/openassetio-core/include/openassetio/BatchElementError.hpp (hunk 3 above)
Comment (feltech) [reply src/openassetio-core/include/openassetio/BatchElementError.hpp]: HTTP status codes as an analogy is a bit tenuous, but a good rule of thumb.  Added a note in c1373efd, how is that?

**Review by foundrytom — APPROVED** [review]
FFTSAMAYL
